definitions:
  user.CreateUserValidator:
    properties:
      confirmation_password:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    required:
    - confirmation_password
    - email
    - full_name
    - password
    type: object
  user.LoginValidator:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  user.RegisterValidator:
    properties:
      confirmation_password:
        type: string
      email:
        type: string
      full_name:
        type: string
      merchant_address:
        type: string
      merchant_name:
        type: string
      merchant_phone:
        type: string
      password:
        type: string
    required:
    - confirmation_password
    - email
    - full_name
    - merchant_address
    - merchant_name
    - merchant_phone
    - password
    type: object
  utils.ResponseModel:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact:
    email: fahrul.fauz@gmail.com
    name: API Support
  termsOfService: http://swagger.io/terms/
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: ping app
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseModel'
      summary: Pinging App
      tags:
      - Default
  /user:
    get:
      consumes:
      - application/json
      description: List user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseModel'
      security:
      - JWTAuth: []
      summary: Get List User
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: Create User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserValidator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseModel'
      security:
      - JWTAuth: []
      summary: Create User
      tags:
      - Users
  /user/{uuid}:
    get:
      consumes:
      - application/json
      description: Detail user
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseModel'
      security:
      - JWTAuth: []
      summary: Get Detail User
      tags:
      - Users
  /user/login:
    post:
      consumes:
      - application/json
      description: login app
      parameters:
      - description: Login User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.LoginValidator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseModel'
      summary: Login User
      tags:
      - Auth
  /user/register:
    post:
      consumes:
      - application/json
      description: register app
      parameters:
      - description: Register User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.RegisterValidator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseModel'
      summary: Register User
      tags:
      - Auth
securityDefinitions:
  JWTAuth:
    in: header
    name: access_token
    type: apiKey
swagger: "2.0"
